### ISSUE TITLE
cqhttp-mirai 配置无效

### ISSUE THREAD

**Issue by rainsmen** [Quan666/ELFChatBot#10]
如题，参照go-http的文件改cqhttp-mirai文件，只配置1080就是没反应，配置/ws/gohttp那个就会提示无法连接到服务，go-http测试正常,大佬能否给看看cqhttp-mirai配置如何设置ws反向，谢谢

**Comment by Quan666** [comment]
主要适配go-cqhttp，其他的比如mirai-http具体我也不太清楚，请自己研究下配置方式。
配置方式应该都是大同小异。端口用8080

**Comment by rainsmen** [comment]
> 主要适配go-cqhttp，其他的比如mirai-http具体我也不太清楚，请自己研究下配置方式。
> 配置方式应该都是大同小异。端口用8080
谢谢大佬回复，主要是这段是否必须完全一致
reverse_url": "ws://127.0.0.1:8080/cqhttp/ws"
默认8080启动的话可能接收不到，然后加上这几个信息的话很多启动不成功，我自己在看看

"ws_reverse_servers": [
    {
      "enabled": true,
      "reverse_url": "ws://127.0.0.1:8080/cqhttp/ws",
      "reverse_api_url": "",
      "reverse_event_url": "",
      "reverse_reconnect_interval": 3000
    }
  ],

**Comment by Quan666** [comment]
要一致，如果换端口的话，插件也要换同样的
