### ISSUE TITLE
配置完ELF_RSS后,ChatBot的BaiduKey调用报错

### ISSUE THREAD

**Issue by DogeNeko** [Quan666/ELFChatBot#15]
1. 先前运行过ELF_RSS程序,而后开始第一次运行Chat程序.
我只添加了BaiduKey,显示"腾讯、百度 闲聊配置出错！请正确配置3check_hostname requires server_hostname".
在填入腾讯Key后,ChatBot能正常运行.

2.后来,卸载了python,重装了环境和python
只添加了BaiduKey,只配置ChatBot,能正常运行.
在此基础上配置ELF_RSS后,再度显示"腾讯、百度 闲聊配置出错！请正确配置3check_hostname requires server_hostname"

  疑似是RSS依赖配置问题导致Chat的BaiduKey识别异常?

**Comment by Quan666** [comment]
没有依赖，应该是你合并配置文件的时候出现了问题。

**Comment by DogeNeko** [comment]
> 没有依赖，应该是你合并配置文件的时候出现了问题。

我没合并配置文件,开了两个nonebot,分别安装依赖所以出错了。
现在问题已经解决了,感谢！
