### ISSUE TITLE
httpx版本>=0.16.0后闲聊出错

### ISSUE THREAD

**Issue by lunzima** [Quan666/ELFChatBot#16]
self._client post完之后会被关闭，httpx升级以后已关闭的client不能重新打开

**Comment by Quan666** [comment]
依赖里面的版本要求是0.17.0，你的是什么版本

**Comment by lunzima** [comment]
降级到0.15.5之后才正常

**Comment by Quan666** [comment]
不应该，我bot是0.18.0版本，你Python什么版本？

**Comment by lunzima** [comment]
Python 3.8.10 on Ubuntu 20.04

**Comment by lunzima** [comment]
本地尝试了一下修复方法，切实有效
sendMsg函数每次调用都再创建一个httpx.AsyncClient

**Comment by Quan666** [comment]
你把你改后的pr上来吧

**Comment by lunzima** [comment]
dirty hack，把proxy支持阉割了

**Comment by lunzima** [comment]
![QQ截图20220518203701](https://user-images.githubusercontent.com/32062239/169040180-c1d881da-f2b7-4b4e-a01e-ece1c90ff668.png)
