### ISSUE TITLE
CHATGPT过长的消息会被吞掉部分

### ISSUE THREAD

**Issue by izumedonabe** [Quan666/ELFChatBot#17]
如题，希望增加一个消息分片功能

**Comment by Quan666** [comment]
gocq的强制分片打开了吗？

**Comment by izumedonabe** [comment]
> gocq的强制分片打开了吗？

打开了，但是打开后群消息发送失败，先显示CQ码转换失败，再显示消息为空。私聊发送可以发送，但是仍然缺失超出字数的部分

**Comment by Quan666** [comment]
关闭试试呢

**Comment by izumedonabe** [comment]
> 关闭试试呢

关闭后群消息可发 但是会被吞掉多余的部分![image](https://user-images.githubusercontent.com/42296908/206120031-dd585eb4-a63b-4622-b69b-a3e5823eeb43.jpeg)

**Comment by Quan666** [comment]
这个是chatgpt的问题

**Comment by izumedonabe** [comment]
不好意思，我刚刚发现它官方就有字数限制，只需要说 继续 它就能往下生成了 感谢解答

**Comment by izumedonabe** [comment]
> 这个是chatgpt的问题
> 
> 

OK 谢谢
