### ISSUE TITLE
仅使用百度或腾讯

### ISSUE THREAD

**Issue by YipSzeho** [Quan666/ELFChatBot#2]
可不可以添加可选配置，只用百度或腾讯呢

**Comment by Quan666** [comment]
默认优先使用百度，不设置百度则使用腾讯。
可以只设置一个

**Comment by YipSzeho** [comment]
我没能申请到腾讯AI的接入，配置文件里不填的话就会提示 缺少app_id参数:请检查请求中是否包含有效的app_id参数，这个怎么办0v0

**Comment by Quan666** [comment]
这是你百度的也没设置对吧？控制台输出截图我看看

**Comment by YipSzeho** [comment]
啊我的错，百度那里忘了添加技能0v0，抱歉！0v0
