### ISSUE TITLE
执行pip install -r requirements.txt后运行bot.py显示ModuleNotFoundError: No module named 'nonebot'

### ISSUE THREAD

**Issue by HETAOSAMA** [Quan666/ELFChatBot#20]
在本地下好所需的包，vscod中显示Import "nonebot.adapters.cqhttp" could not be resolved

**Comment by HETAOSAMA** [comment]
服务器系统为centos7 python版本为3.8.3

**Comment by Quan666** [comment]
下载最新的 requirements.txt 后再试试

**Comment by HETAOSAMA** [comment]
我正在下载，我这边还有一个问题chatGPT的token应该放在哪里呢，.env.prod是两年前的了

**Comment by ZhaoLizz** [comment]
```elfchatbot\plugins\ELFChatBot\config.py```

**Comment by HETAOSAMA** [comment]
感谢

**Comment by HETAOSAMA** [comment]
研究了一下，cqhttp在a16之后就弃用了 现在叫onebot
