### ISSUE TITLE
纯小白 到了参照部署ELF-RSS2就不会弄了 能详细说明一下吗

### ISSUE THREAD

**Issue by qyhao233** [Quan666/ELFChatBot#3]
秋梨膏

**Comment by Quan666** [comment]
部署教程我认为已经很清楚了。。。

**Comment by qyhao233** [comment]
部署问题已经解决了 谢谢 因此我还鼓弄了一会python...
然后新问题来了


有时候启动的时候无法正常聊天，这个该如何解决

**Comment by qyhao233** [comment]
![IF0JM$N1 $(E YP@5JSBL$O](https://user-images.githubusercontent.com/36359905/105053829-5745d080-5aac-11eb-8e92-98095444e86a.png)

**Comment by qyhao233** [comment]
找到问题了,在.env.prod把OpendRandom=设置为true时才会发生这样的情况
机器人直接停止工作.. 这个会进行修复吗

**Comment by Quan666** [comment]
贴上详细的错误日志截图以及复现步骤

**Comment by qyhao233** [comment]
好像是这里的问题又似乎不是这里的问题
因为在false状态也偶然会出现这种情况 true是经常
emmm抱歉 我是小白
反正重开的话有时候会什么话都不说 或者一连炮发几段话
` 01-20 21:51:26 [INFO] nonebot | CQHTTP | 69874207 [message.private.friend]: Mess
age 481211734 from 767832567 "你好"
01-20 21:51:26 [DEBUG] nonebot | Checking for matchers in priority 0...
01-20 21:51:26 [INFO] nonebot | Event will be handled by <Matcher from ELF_bot,
type=message, priority=0, temp=True>
01-20 21:51:26 [DEBUG] nonebot | Running matcher <Matcher from ELF_bot, type=mes
sage, priority=0, temp=True>
01-20 21:51:26 [INFO] nonebot | Event will be handled by <Matcher from ELF_bot,
type=message, priority=0, temp=True>
01-20 21:51:26 [DEBUG] nonebot | Running matcher <Matcher from ELF_bot, type=mes
sage, priority=0, temp=True>
01-20 21:51:26 [ERROR] ELF_bot | {'code': '-1'}
01-20 21:51:27 [DEBUG] nonebot | CQHTTP | Calling API send_msg
01-20 21:51:27 [INFO] nonebot | Matcher <Matcher from ELF_bot, type=message, pri
ority=0, temp=True> running complete
01-20 21:51:27 [DEBUG] nonebot | CQHTTP | Calling API send_msg
01-20 21:51:28 [INFO] nonebot | Matcher <Matcher from ELF_bot, type=message, pri
ority=0, temp=True> running complete
01-20 21:51:28 [DEBUG] nonebot | Stop event propagation`
![QQ截图20210120220746](https://user-images.githubusercontent.com/36359905/105186171-655b2600-5b6c-11eb-85a3-a7c5c90e3530.png)
~~或许是老朽打开方式不对？在开机第一次打开直接点×关闭再打开一次会出错？~~

**Comment by qyhao233** [comment]
![QQ截图20210120214332](https://user-images.githubusercontent.com/36359905/105186370-9a677880-5b6c-11eb-8b94-ee8992a588a9.png)

**Comment by Quan666** [comment]
确保你的api key有效
看你提供的信息可能是你apikey的问题

**Comment by qyhao233** [comment]
似乎是这样 我使用的是百度的闲聊增强版beta 在智能对话测试下似乎有点问题
谢谢
