### ISSUE TITLE
在连续性发出多条信息后之后的单次回复将一连炮发出三条信息

### ISSUE THREAD

**Issue by qyhao233** [Quan666/ELFChatBot#5]
像这样
![QQ截图20210121171101](https://user-images.githubusercontent.com/36359905/105329046-aeae8280-5c0b-11eb-93ad-769aa4a7bfb2.png)
有几秒延迟的发送不会出现任何问题
但一连串发出多条消息后，之后发送的每条消息都将回复三次
![QQ截图20210121171150](https://user-images.githubusercontent.com/36359905/105329133-c7b73380-5c0b-11eb-9052-7cef6afd0875.png)
![QQ截图20210121171237](https://user-images.githubusercontent.com/36359905/105329271-ecaba680-5c0b-11eb-892d-d0e410eb13d7.png)
【已经将腾讯和百度的api全部填写完毕~~ 顺带一提可以仅使用百度的API吗 如果腾讯api以.env.prod的原始文件来填的话总是显示APPID为空，已经提交了两个问题会不会有丶多余~~】

**Comment by Quan666** [comment]
这个问题我复现了，我研究下怎么修复，你暂时只能是尽量不要太快（各种意义上的快）

关于仅使用百度api 见 #2
不使用设为空即可，就是=后面设置为""
提交issue很好，没什么多余的

**Comment by qyhao233** [comment]
就算腾讯那两段=后面全部填""仍然无法单独使用百度
发送消息显示:"缺少app_id参数:请检查请求中是否包含有效的app_id参数"
最近重感冒 今天好点了重新测试一下才发现的

**Comment by Quan666** [comment]
> 就算腾讯那两段=后面全部填""仍然无法单独使用百度
> 发送消息显示:"缺少app_id参数:请检查请求中是否包含有效的app_id参数"
> 最近重感冒 今天好点了重新测试一下才发现的

我这里并没有复现，把你配置打码后贴上来看看

**Comment by qyhao233** [comment]
`HOST=0.0.0.0  # 配置 NoneBot 监听的 IP/主机名
PORT=8080  # 配置 NoneBot 监听的端口
DEBUG=true  # 开启 debug 模式 **请勿在生产环境开启**
SUPERUSERS=["6xxxxxx]  # 配置 NoneBot 超级用户 # 管理员qq,支持多管理员，逗号分隔 注意，启动消息只发送给第一个管理员
NICKNAME=["elf", "ELF"]  # 配置机器人的昵称
COMMAND_START=["","/"]  # 配置命令起始字符
COMMAND_SEP=["."]  # 配置命令分割字符

# Custom Configs
# PROXY 已经删除
# PROXY = '127.0.0.1:7890' # 如果你开启了代理请务必设置此项，没开务必删除 值（'127.0.0.1:7890'）
BanGroup=[] # 群组黑名单 示例 [123,123]
# 百度，默认优先使用百度
baidu_api_key="FXExxxxxxxxx" # API Key
baidu_secret_key="WZVxxxxxxxx" # Secret Key
baidu_bot_id="Sxxxx" # # 你闲聊机器人的 id S开头
# 腾讯
tx_app_id=""
tx_appkey=""

# 娱乐功能
# 随机回复功能开启后会随机回复某一条群消息。容易造成恐慌，请谨慎开启！！！
OpendRandom=true
RandomProbability=0.1 # 随机回复概率，0.1%
# MYELF博客地址 https://myelf.club
# 出现问题请在 GitHub 上提 issues
# 项目地址 https://github.com/Quan666/ELFChatBot`

**Comment by qyhao233** [comment]
![QQ截图20210125154130](https://user-images.githubusercontent.com/36359905/105675262-d3fd0280-5f23-11eb-8c36-40bdadae59ea.png)

**Comment by Quan666** [comment]
设置为 
```
tx_app_id= 
tx_appkey=""
```
试试

**Comment by qyhao233** [comment]
未能解决问题。。

**Comment by Quan666** [comment]
启动时会输出读取到的配置文件，你打码后发出来看看
还有错误也截图看看

**Comment by qyhao233** [comment]
配置文件
链接：https://pan.baidu.com/s/1A9yS81OpAu9Mm33peAN9Cg 
提取码：m4eb 
![QQ截图20210125160506](https://user-images.githubusercontent.com/36359905/105678057-a5812680-5f27-11eb-9517-bd6c7911dc18.png)
只有这一段吧

**Comment by Quan666** [comment]
你这是百度api调用失败然后去调用tx导致的。
![image](https://user-images.githubusercontent.com/32663291/105678279-eaa55880-5f27-11eb-9d7e-44fb311bbef7.png)
如果你每次都会调用失败，去检查你百度apikey的正确性

**Comment by qyhao233** [comment]
谢谢 我是baka
secret_key最后面少复制了一位字母

**Comment by qyhao233** [comment]
话说回来 伪造合并信息的那个怎么操作 我看了半天不知道怎么整
