### ISSUE TITLE
当机器人与好友聊天时，如果该好友在其他群聊内发送了一条消息，则会被回复

### ISSUE THREAD

**Issue by qyhao233** [Quan666/ELFChatBot#6]
已确认:"OpendRandom=false"
目前已确认发生过两次这样的现象
![QQ截图20210121200750](https://user-images.githubusercontent.com/36359905/105349305-7a938b80-5c24-11eb-88c8-9e7ad62e21bc.png)
应该不难重现 只需要使机器人跟好友聊天 好友在与有机器人存在的群聊聊天机器人便会自动回复

**Comment by Quan666** [comment]
这是保留的特性，我还在考虑是不是要做限制。

**Comment by qyhao233** [comment]
建议增加一个开关
（顺便加一个如果群友发送了"@机器人 +信息"的消息则自动闲聊的功能呗？

**Comment by Quan666** [comment]
> 建议增加一个开关
> （顺便加一个如果群友发送了"@机器人 +信息"的消息则自动闲聊的功能呗？ 

@机器人+信息会触发闲聊
