### ISSUE TITLE
一直提示Module ELFChatBot has been loaded by other plugin! Ignored

### ISSUE THREAD

**Issue by lemonno2333** [Quan666/ELFChatBot#8]
不管是不是第一次打开elfchatbot都提示Module ELFChatBot has been loaded by other plugin! Ignored，重新启动后也一样，并且无法使用
![屏幕截图 2021-01-30 160614](https://user-images.githubusercontent.com/49359040/106351111-24ee6b80-6315-11eb-833c-72378ccfe2e9.jpg)

**Comment by Quan666** [comment]
付上完整插件目录截图，nonebot版本，

**Comment by lemonno2333** [comment]
go-cqhttp-v0.9.39
![屏幕截图 2021-01-30 220120](https://user-images.githubusercontent.com/49359040/106358448-39e3f280-6347-11eb-9d06-c6f5ced76265.jpg)

**Comment by Quan666** [comment]
运行 pip list，然后截图

**Comment by Quan666** [comment]
还有你是怎么运行的

**Comment by lemonno2333** [comment]
![屏幕截图 2021-01-30 231427](https://user-images.githubusercontent.com/49359040/106359973-f68e8180-6350-11eb-9ffe-fbc07f400e52.jpg)
在powershell里面nb run

**Comment by Quan666** [comment]
应该是你go和插件没有连接到，排查下go的配置，还有端口应该是8080

**Comment by lemonno2333** [comment]
go里面的http端口是5700,ws端口是6700,反向ws没有开,是不是go-cqhttp没有nonebot的协议啊

**Comment by lemonno2333** [comment]
搞好了，但是腾讯ai平台不能添加新应用了，现在提示检查appid是否有效

**Comment by Quan666** [comment]
> 搞好了，但是腾讯ai平台不能添加新应用了，现在提示检查appid是否有效

那就只用百度
务必确保api key填写正确

**Comment by lemonno2333** [comment]
是直接用#注释掉还是“”留空啊，好像这两种都会报错

**Comment by Quan666** [comment]
留空就行
还报错说明你百度apikey有问题，请参考 #5

**Comment by lemonno2333** [comment]
啊是我忘了加技能，谢谢大佬
